#+hugo_base_dir: .
* A goddam blog
  :PROPERTIES:
  :EXPORT_HUGO_SECTION:
  :END:
  
** posts
   :PROPERTIES:
   :EXPORT_HUGO_SECTION: posts
   :END:
   
*** posts
    :PROPERTIES:
    :EXPORT_FILE_NAME: _index
    :EXPORT_HUGO_AUTO_SET_LASTMOD: t
    :END:
    
    These are classical long-form wi-fi high rise hippie chippie
    brogrammer yo hammer hobble gobble of blubber gobbling logs
    long while logging global blahs blog posts.

    I've tried to use the "tags" properly so they're probably
    going to be random essays spanning varying subjects.
    
*** One bad night
    :PROPERTIES:
    :EXPORT_FILE_NAME: bad-night
    :EXPORT_HUGO_AUTO_SET_LASTMOD: t
    :END:
   
    Someone is here... I think!
   
*** Another bad night
    :PROPERTIES:
    :EXPORT_FILE_NAME: another
    :EXPORT_HUGO_AUTO_SET_LASTMOD: t
    :END:
    
    Yet another bad night! How unfortunate
    
** notes
   :PROPERTIES:
   :EXPORT_HUGO_SECTION: notes
   :END:
   
*** notes
    :PROPERTIES:
    :EXPORT_FILE_NAME: _index
    :END:
    This section is a ever-updating ever changing collection
    of notes. If I'm doing my job right, they'll be super
    interconnected like wikipedia. This style of notetaking
    will hopefully create an emergent intelligence much 
    smarter than myself. I am confident this will work
    because I read about it on the internet.

    So I join the ranks of those super
    smart people - the best researchers! Most known
    for their great and interconnected notes.

    With the exception, of course, of Literally Every Researcher I Know.
    
    Anyways here are the broad categories... 
      - Rationality
      - Meditation
      - Hacking

    The plan is to make a page accessible from any other page.
    
*** Forward-Fake memories
    :PROPERTIES:
    :EXPORT_FILE_NAME: forward-fake-memories
    :EXPORT_HUGO_AUTO_SET_LASTMOD: t
    :END:
     
    These are memories (or, possible future scenarios)
    which have not happened yet. For another topic see [[*Backward-Fake memories]]

*** Backward-Fake memories
    :PROPERTIES:
    :EXPORT_FILE_NAME: backwards-fake-memories
    :EXPORT_HUGO_AUTO_SET_LASTMOD: t
    :END:
    
    Opposite to [[*Forward-Fake memories]], backward fake memories imagine strange
    scenarios that /could have happened in the past/ but didn't. 
** TIL
   :PROPERTIES:
   :EXPORT_HUGO_SECTION: TIL
   :END:
   
*** TIL
    :PROPERTIES:
    :EXPORT_FILE_NAME: _index
    :TOC: true
    :END:
    
**** Today-I-learned
     These are little shortform learnings... we learn a little
     everyday :)
   
*** sizeof() is a macro, or, how does one understand hello world?
    :PROPERTIES:
    :EXPORT_FILE_NAME: sizeof-is-a-macro
    :END:

   
****  Hello, bit sizes? 
     I remember one of the assignments (in fact,
     literally the /first/ assignment at my university ever - we skipped
     "hello world" for some reason)
     was to print the bit sizes of various types. So, after much pain, we went ahead and
     wrote 
    
     #+begin_src C
     #include<stdio.h>
     int main() {
       printf("An int is %d bits long \n", sizeof(int));
       printf("And float is %d bits long \n", sizeof(float));
       printf("And char is %d bits long \n", sizeof(char));
     }
     #+end_src

     and after learning (in the most basic sense) how to use =gcc=, we got out
     
     #+begin_src 
     An int is 4 bits long
     And float is 4 bits long
     And  char is 1 bits long
     #+end_src

     Afterwards, we learnt about functions. And I even wrote my
     *own* function! Of course, since I am a prodigy of programming
     it took my no time to create this absolute beauty:
     #+begin_src C
      #include<stdio.h>
      int soWhenDoWeGetGirlfriends(int number) {
        return number + 3;
      }
      int main(){
        printf("%d\n", soWhenDoWeGetGirlfriends(3));
      }
     #+end_src

     #+attr_quote: 
     : 6

     Ah so that's pretty easy. I guess =printf= and =sizeof= are two
     other functions that some old guys wrote. Something with that =main= 
     function was also important. Well, here I am, totally
     on their level since I've also written /my/ function.
    
     It wasn't until embarassingly later that I realized that *none* of those
     functions are like each other.
   
****  Breaking it down
     
     Let's start with the abomination which was my function.
     This is a standard function. Strict return type, strict input, strict computer science professors.
     If I wrote =soWhenDoWeGetGirlfriends(4, "please");=, my compiler would throw error,
     my lower palm would make an impact with my forehead, and I'd start again.

     
    
     Next, let's look at the =printf=. This is just some function defined in
     =stdio.h=, right? Well actually, and I'm not sure how I didn't notice this
     despite using =printf= every single time I used C, that it can take a *variable* amount
     of arguments. 
     
     I mean, duh, of course it can. I've been putting a random amount of floats, ints,
     and chars all the time. Yet, for some reason, I decided "yep that's normal, and I
     will never try to create a function with variable parameters myself, because that
     is impossible and has never been done before. Now I will =printf= debug this code."

     <article>
     Something
     </article>
